name: eda-sandbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: robsondouglas
        password: ${{ secrets.DOCKER_PWD }}
    - name: BUILD and PUSH BDMem image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./.devcontainer/dockerfile
        build-args: app_name=build-app-bd
        tags: robsondouglas/eda-sandbox-bdmem:latest, robsondouglas/eda-sandbox-bdmem:${{github.run_number}}
