name: eda-sandbox

on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USR }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: BUILD and PUSH BD image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./.devcontainer/dockerfile
        build-args: app_name=build-app-bd
        tags: ${{ secrets.DOCKER_USR }}/eda-sandbox-bdmem:latest, ${{ secrets.DOCKER_USR }}/eda-sandbox-bdmem:${GITHUB_REF/refs\/tags\//}
    - name: BUILD and PUSH API Vote image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./.devcontainer/dockerfile
        build-args: app_name=build-app-api
        tags: ${{ secrets.DOCKER_USR }}/eda-sandbox-bdmem:latest, ${{ secrets.DOCKER_USR }}/eda-sandbox-apivote:${GITHUB_REF/refs\/tags\//}
    - name: BUILD and PUSH WORKER Vote image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./.devcontainer/dockerfile
        build-args: app_name=build-app-worker-vote
        tags: ${{ secrets.DOCKER_USR }}/eda-sandbox-bdmem:latest, ${{ secrets.DOCKER_USR }}/eda-sandbox-workervote:${GITHUB_REF/refs\/tags\//}
    - name: BUILD and PUSH WORKER Aggregator image
      uses: docker/build-push-action@v3
      with:
        push: true
        file: ./.devcontainer/dockerfile
        build-args: app_name=build-app-worker-aggregator
        tags: ${{ secrets.DOCKER_USR }}/eda-sandbox-bdmem:latest, ${{ secrets.DOCKER_USR }}/eda-sandbox-workeraggregator:${GITHUB_REF/refs\/tags\//}
